### get persons json
GET http://localhost:3001/api/persons

### get info page
GET http://localhost:3001/info

### delete person
DELETE http://localhost:3001/api/persons/641de59c3fa81b2e4ca9660a

### add person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alan Turing",
    "number": "040-139234"
}

### add person without number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ash Ketchum",
    "number": ""
}

### get person that doesn't exist
GET http://localhost:3001/doesnt_exist